<script src="{{asset('js/jquery-3.3.1.min.js')}}"></script>
<script src="{{asset('vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<script src="{{asset('vendor/OwlCarousel/owl.carousel.js')}}"></script>
<script src="{{asset('vendor/charts/Chart.min.js')}}"></script>
<script src="{{asset('vendor/semantic/semantic.min.js')}}"></script>
<script src="{{asset('js/custom.js')}}"></script>
<script src="{{asset('js/night-mode.js')}}"></script>
{{-- <script src="{{asset('js/chart.js')}}"></script> --}}
<script src="{{asset('vendor/jquery-ui-1.12.1/jquery-ui.js')}}"></script>
<script src="{{asset('js/jquery-steps.min.js')}}"></script>
<script src="{{mix('/js/app.js')}}"></script>